version: "3.9"
services:
  postgres:
    container_name: "exp-postgres"
    image: postgres:14
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - .env
    volumes:
      - exp-tracker-postgres:/var/lib/postgresql/data
      # - ./dump/expense_20220620.sql:/docker-entrypoint-initdb.d/expense_20220620.sql

  pgadmin:
    container_name: "exp-pgadmin"
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    
  mariadb:
    container_name: "exp-mariadb"
    image: mariadb:latest
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - exp-tracker:/var/lib/mysql
      # - ./dump/expense_20220620.sql:/docker-entrypoint-initdb.d/expense_20220620.sql

  core:
    container_name: "exp-core"
    image: kehvinbehvin/expensetracker:5827283
    ports:
      - "8080:8080"
    env_file:
      - .env.core
    volumes:
      - ../expense-tracker/build:/usr/src/app/build

volumes:
  exp-tracker:
  exp-tracker-postgres:
